### ISSUE TITLE
Uncaught Error: Adding a pane item with URI 'D:/git\nytek_crm_client\src\components\organizations...

### ISSUE THREAD

**Issue by Cr0WD** [oriolmirosa/open-files#11]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 ia32
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.5.4

### Stack Trace

Uncaught Error: Adding a pane item with URI 'D:\git\nytek_crm_client\src\components\organizations\EditForm.js' that has already been destroyed

```
At C:\Users\fresh\AppData\Local\atom\app-1.17.0\resources\app\src\pane.js:493

Error: Adding a pane item with URI 'D:\git\nytek_crm_client\src\components\organizations\EditForm.js' that has already been destroyed
    at Pane.module.exports.Pane.addItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:493:1)
    at Pane.module.exports.Pane.activateItem (~/AppData/Local/atom/app-1.17.0/resources/app/src/pane.js:468:1)
    at /packages/open-files/lib/open-files-pane-view.js:179:21)
```

### Commands

```
     -0:08.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-bootstrap3 1.2.12 
atom-django 0.3.2 
atom-formatter-jsbeautify 1.1.2 
atom-jade 0.3.0 
atom-material-syntax 1.0.6 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.0.3 
auto-indent 0.5.0 
autoclose-html 0.23.0 
autocomplete-html-entities 0.1.0 
autocomplete-json 5.5.0 
autocomplete-modules 1.6.10 
autocomplete-paths 1.0.5 
autocomplete-python 1.8.63 
autoupdate-packages 1.3.1 
color-picker 2.2.5 
django-templates 0.5.0 
emmet 2.4.3 
emmet-jsx-props 1.2.5 
file-icons 2.1.6 
git-projects 1.17.0 
jade-bootstrap3-snippets 0.3.0 
jQuery 1.2.5 
jsx-comment 0.2.0 
language-django 0.1.1 
merge-conflicts 1.4.5 
minimap 4.28.2 
open-files 0.5.4 
pigments 0.39.1 
react 0.16.2 
react-snippets 0.7.2 
tool-bar 1.1.0 
tool-bar-almighty 0.8.2 
```

**Comment by oriolmirosa** [comment]
This should be fixed now. Please re-open if it's still giving you trouble. Thanks for reporting!
