### ISSUE TITLE
Plugin fails to load if "Settings" is open

### ISSUE THREAD

**Issue by Goodwine** [oriolmirosa/open-files#2]
I noticed that when you open your editor and the "settings" tab/page/whatever is open, the plugin won't load because it tries to get the "path" from the pane item, and "settings" doesn't have a path.

The exception thrown is:

```
Uncaught (in promise) TypeError: item.getPath is not a function
    at ~/.atom/packages/open-files/lib/open-files-pane-view.js:64:48
    at Pane.module.exports.Pane.observeItems (/opt/atom/resources/app.asar/src/pane.js:211:9)
    at OpenFilesPaneView.setPane (~/.atom/packages/open-files/lib/open-files-pane-view.js:50:25)
    at OpenFilesView.addTabGroup (~/.atom/packages/open-files/lib/open-files-view.js:28:9)
    at ~/.atom/packages/open-files/lib/open-files-view.js:17:9
    at PaneContainer.module.exports.PaneContainer.observePanes (/opt/atom/resources/app.asar/src/pane-container.js:92:9)
    at Workspace.module.exports.Workspace.observePanes (/opt/atom/resources/app.asar/src/workspace.js:374:33)
    at new OpenFilesView (~/.atom/packages/open-files/lib/open-files-view.js:16:35)
    at ~/.atom/packages/open-files/lib/open-files.js:19:25
```

**Comment by Goodwine** [comment]
BTW the current workaround is to close the "Settings" tab (or any other tab that could have no path) and restart/refresh the editor (Normally you can refresh with Ctrl+Alt+R).

**Comment by oriolmirosa** [comment]
Thanks for the report. I added a try-catch clause around item.getPath() so that the package now works and lists the 'settings' tab.
