### ISSUE TITLE
Uncaught TypeError: Cannot read property 'item' of undefined

### ISSUE THREAD

**Issue by nsatija** [oriolmirosa/open-files#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.2

### Stack Trace

Uncaught TypeError: Cannot read property 'item' of undefined

```
At /Users/Nick/.atom/packages/open-files/lib/open-files-pane-view.js:86

TypeError: Cannot read property 'item' of undefined
    at /packages/open-files/lib/open-files-pane-view.js:86:53)
    at HTMLUListElement.dispatch (/packages/open-files/node_modules/jquery/dist/jquery.js:5206:27)
    at HTMLUListElement.elemData.handle (/packages/open-files/node_modules/jquery/dist/jquery.js:5014:28)
```

### Commands

```
     -2:39.6.0 snippets:expand (input.hidden-input)
     -2:39.6.0 editor:indent (input.hidden-input)
     -2:39.4.0 snippets:next-tab-stop (input.hidden-input)
     -2:39.4.0 snippets:expand (input.hidden-input)
     -2:39.4.0 editor:indent (input.hidden-input)
     -2:38.2.0 core:backspace (input.hidden-input)
     -2:33.4.0 core:save (input.hidden-input)
     -1:36.3.0 editor:newline (input.hidden-input)
  2x -1:34.6.0 intentions:highlight (input.hidden-input)
     -1:05.5.0 core:backspace (input.hidden-input)
     -1:04.9.0 core:move-up (input.hidden-input)
 13x -1:04.4.0 editor:move-to-end-of-screen-line (input.hidden-input)
 15x -0:59.9.0 core:delete (input.hidden-input)
     -0:39.9.0 core:copy (input.hidden-input)
  2x -0:39.2.0 core:paste (input.hidden-input)
     -0:30.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-minify 0.8.0 
autoclose-html 0.23.0 
busy-signal 1.4.3 
color-picker 2.2.5 
intentions 1.1.2 
jade 1.1.0 
jade-beautify 0.1.5 
language-pug 0.0.21 
lebab 0.10.0 
lebab-convert 0.9.0 
linter 2.2.0 
linter-ui-default 1.6.2 
open-files 0.8.2 
open-html-in-browser 0.1.0 
opened-files 0.3.6 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
rainbow-tabs 2.2.1 
tabs-closer 0.16.0 
tidy-tabs 0.4.0 
tree-view-open-files 0.3.0 
uglify 1.3.1 
```

**Comment by oriolmirosa** [comment]
Thanks for reporting this, @nsatija. I will need some more info in order to debug this:

- Can you tell me what files and panels you had open when this happened?
- What file were you modifying?
- Can you reproduce the bug?
- I see that you had the opened-files package installed as well. It is possible that that's where the problem comes from. Have you tried to run only the open-files package and disable opened-files? If so, does the problem persist?

Thanks!

**Comment by tobiastom** [comment]
I think I have the same error. I did click on the `X` to close the Settings "document".

**Comment by mfour-merickson** [comment]
+1 on this error.  

For me, it happens when I click the X, or simply select a file.  What is disheartening, this same issue occurred from the package you forked so you might have converted by CoffeeScript to ES6

**Comment by oriolmirosa** [comment]
Thanks for your comments and sorry for the delay in responding to some of you. I'm in the middle of several big life transitions and things are crazy. As I mentioned earlier in this thread, this is frustrating for me because I don't experience the problem, so I don't know how to debug it. It would be really helpful if someone could give me more details:

- Does the problem happen **every time** that you click the X?
- Are you talking about the X in the open files panel, on the tab, or both?
- What panels and files do you have open?
- Have you been opening and closing files before the problem appears? My sense is that, after opening and closing some combination of files and panels, the package loses sight of what files/panels are open and when you try to close a file that is not registered you get the error. In order to fix this, I need to figure out what is the pattern that leads to the mismatch between open files and the list tracked by the package. I would really appreciate if you could help me identify the pattern of opening and closing files/panels that takes place **before** the error is raised.

Thanks!

**Comment by JossueValar** [comment]
1. Yes it does.
2. The X in the open files panel.
3. It was just installed and was working fine until I closed Atom, then it happened. My guess is that my atom didn't install right in some way because I was having problems even with tree-view but I don't know.
4. I first closed the tabs after atom booted, then I couldn't see the side panel so I toggled it and there were the tabs I just closed, when I proceed to close them the bug appears.

I don't know if this was solved already since it's such an old post, but if you could help me that'd be awesome! :D

Edit:
I don't know if it should appear in the menu bas where it says packages but it doesn't haha. If I look for it in the settings, disable it and then enable it it starts working again.

**Comment by jdpipe** [comment]
I got this error when clicking a file in the 'open-files' list, then typing 'ctrl-w' to close the file. Actually I closed one file, then I closed another one by the same message. There is a noticeable delay after each 'ctrl-w' before the open-files list's animation removes the file and closes the gap. The gap is long enough to make one wonder if one had clicked successfully or not...
