### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by Jole91** [oriolmirosa/open-files#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.2

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /home/jo/.atom/packages/open-files/lib/open-files-view.js:71

TypeError: Cannot set property 'innerHTML' of null
    at /packages/open-files/lib/open-files-view.js:71:30
```

### Commands

```
  4x -2:45.6.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
color-picker 2.2.5 
emmet 2.4.3 
open-files 0.8.2 
open-in-browsers 0.0.30 
```

**Comment by oriolmirosa** [comment]
Thanks for reporting this, @Jole22 . I will need some more info in order to debug this:

- Can you tell me what files and panels you had open when this happened?
- What file were you modifying?
- Can you reproduce the bug?

Thanks!

**Comment by MaherAlshaar** [comment]
what should i do now

**Comment by andrew-walker-au** [comment]
I see the same issue - can reproduce by opening a markdown-preview window and then when I close it I get this error every time.
[Enter steps to reproduce:]

1. Open markdown preview of any .md file
2. Close markdown preview

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.4


### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of null

```
At /Users/walkea13/.atom/packages/open-files/lib/open-files-view.js:71

TypeError: Cannot set property 'innerHTML' of null
    at /packages/open-files/lib/open-files-view.js:71:30
```

### Commands

```
  5x -5:54.6.0 core:backspace (input.hidden-input)
  2x -5:52.5.0 core:move-down (input.hidden-input)
  5x -5:51.7.0 core:move-right (input.hidden-input)
  2x -5:48.8.0 core:backspace (input.hidden-input)
     -5:46.4.0 core:move-down (input.hidden-input)
  6x -5:46.1.0 core:move-up (input.hidden-input)
 38x -5:22.7.0 core:move-left (input.hidden-input)
  3x -5:18.2.0 core:move-up (input.hidden-input)
  6x -5:17.4.0 core:move-down (input.hidden-input)
  2x -5:15.8.0 core:move-right (input.hidden-input)
     -5:15.2.0 core:move-down (input.hidden-input)
  2x -5:15 core:move-left (input.hidden-input)
     -5:14.4.0 core:move-down (input.hidden-input)
  2x -5:14.2.0 core:move-right (input.hidden-input)
  3x -5:13.5.0 core:move-up (input.hidden-input)
     -4:55.2.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
colorful-json 1.1.0 
ide-yaml 0.7.1 
open-files 0.8.4 
pp-markdown 0.0.2 
```
