### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by downeyfe** [oriolmirosa/open-files#24]
Steps to reproduce

1. Have unstaged changes visible in the Github integration pane
2. Double-click on a file to stage it
3. About 50% of time the error will appear

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.2

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\frances.downey\AppData\Local\atom\app-1.22.1\resources\app\node_modules\event-kit\lib\emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at StubItem.onDidChangeTitle (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/github/lib/atom-items/stub-item.js:125:31)
    at /packages/open-files/lib/open-files-pane-view.js:286:29
    at Config.module.exports.Config.observeKeyPath (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (~/AppData/Local/atom/app-1.22.1/resources/app/src/config.js:155:27)
    at /packages/open-files/lib/open-files-pane-view.js:232:21
```

### Commands

```
     -0:59.7.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:59.7.0 autocomplete-plus:confirm (input.hidden-input)
     -0:55.3.0 core:move-right (input.hidden-input)
     -0:54.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:54.8.0 editor:newline (input.hidden-input)
     -0:51.6.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:51.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:46.1.0 core:move-right (input.hidden-input)
     -0:45.8.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:45.8.0 editor:newline (input.hidden-input)
     -0:41.3.0 core:move-right (input.hidden-input)
     -0:40.6.0 core:backspace (input.hidden-input)
     -0:40.5.0 markdown-writer:insert-new-line (input.hidden-input)
     -0:40.5.0 editor:newline (input.hidden-input)
  8x -0:33.5.0 intentions:highlight (input.hidden-input)
     -0:32.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-shortcuts 0.0.2 
auto-detect-indentation 1.3.0 
autocomplete-modules 1.8.0 
busy-signal 1.4.3 
cucumber 0.6.0 
cucumber-autocomplete 0.7.2 
cucumber-step 0.2.0 
editorconfig 2.2.2 
emmet 2.4.3 
expand-region 0.4.0 
file-icons 2.1.14 
git-blame 1.3.1 
highlight-selected 0.13.1 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.12.2 
language-babel 2.80.3 
language-cshtml 0.3.0 
linter 2.2.0 
linter-eslint 8.4.0 
linter-ui-default 1.6.10 
markdown-writer 2.7.3 
minimap 4.29.7 
open-files 0.8.2 
prettier-atom 0.43.0 
pristine-ui 1.1.11 
pure-syntax 0.3.0 
sort-lines 0.18.0 
surround-with 0.0.3 
sync-settings 0.8.3 
toggler 0.3.0 
```

**Comment by Xrave** [comment]
[Enter steps to reproduce:]
Have github Plus installed. 

Click unstaged changes and look at the content of the unstaged change. 

This error appears. (nothing seems to be broken tho). 

**Atom**: 1.21.1 x64
**Electron**: 1.6.15

**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.2


### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at StubItem.onDidChangeTitle (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/atom-items/stub-item.js:125:31)
    at /packages/open-files/lib/open-files-pane-view.js:286:29
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:674:13)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:155:27)
    at /packages/open-files/lib/open-files-pane-view.js:232:21
```

### Commands

```
     -3:34.1.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
     -1:20.4.0 command-palette:toggle (div.panels-item)
     -1:18.1.0 core:select-all (input.hidden-input)
     -1:17.4.0 core:backspace (input.hidden-input)
     -1:14.1.0 core:move-down (input.hidden-input)
     -1:13.8.0 core:move-up (input.hidden-input)
     -1:13.5.0 core:confirm (input.hidden-input)
     -1:13.5.0 sync-settings:backup (div.panels-item)
     -1:11.3.0 command-palette:toggle (div.panels-item)
     -1:09.5.0 core:confirm (input.hidden-input)
     -1:09.5.0 sync-settings:check-backup (div.panels-item)
  2x -1:05.2.0 core:close (div.panels-item)
     -0:48.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
activate-power-mode 2.6.0 
advanced-open-file 0.16.7 
ariake-dark-syntax 0.1.3 
ascii-art 1.2.0 
atom-beautify 0.30.9 
atom-html-preview 0.2.5 
atom-pair 2.0.13 
atom-typescript 11.0.10 
auto-detect-indentation 1.3.0 
autoclose-html 0.23.0 
autocomplete-js-import 1.4.0 
autocomplete-modules 1.8.0 
autocomplete-python 1.10.5 
browser-plus 0.0.98 
busy-signal 1.4.3 
code-peek 1.4.21 
command-toolbar 1.0.12 
custom-title 1.0.1 
emmet 2.4.3 
fancy-bracket-matcher 2.1.0 
figlet 0.5.4 
file-icons 2.1.14 
flatten-json 0.1.5 
fold-comments 0.6.0 
fonts 3.0.3 
git-plus 7.10.0 
highlight-line 0.12.0 
highlight-selected 0.13.1 
Hydrogen 2.1.1 
hyperclick 0.1.5 
intentions 1.1.5 
isotope-ui 2.8.5 
js-hyperclick 1.12.2 
jupyter-notebook 0.0.10 
language-gradle 0.0.5 
language-scala 1.1.9 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.6.10 
minimap 4.29.7 
minimap-cursorline 0.2.0 
minimap-highlight-selected 4.6.1 
monokai-seti 0.9.0 
nebula-syntax 0.4.5 
nebula-ui 0.9.2 
nucleus-dark-ui 0.12.3 
open-files 0.8.2 
open-recent 5.0.0 
package-cop 0.2.10 
pig 1.0.0 
pigments 0.40.2 
pristine-ui 1.1.11 
prompt-big-file 0.4.0 
pure-syntax 0.3.0 
rainbow-tabs 2.5.1 
rest-client 1.3.1 
seti-ui 1.9.0 
sort-lines 0.18.0 
sync-settings 0.8.3 
tree-view-autoresize 2.3.0 
tree-view-open-files 0.3.0 
vue-hyperclick 0.2.0 
xatom-debug 1.6.11 
xatom-debug-nodejs 0.9.3 
xatom-syntax 0.3.0 
xatom-ui 0.3.0 
```

**Comment by oriolmirosa** [comment]
Thanks for reporting this issue. As with other similar bugs with the package, I'm a bit at a loss because I'm unable to reproduce the problem on my machine, so it's hard to debug. Would you mind letting me know:

1) what your configuration for the package is (sort order, delay, animation duration, collapsable)
2) what other files are open, and what files did you recently open or close

Thanks!

**Comment by downeyfe** [comment]
Sure, here's my config - animation duration: default (300), collapsable: true, delay: default (1000), sort order: default (base, ext, dir).

As for open files, I've seen it happen with javascript files because I use them the most, but it's probably happened a few times with HTML/CSS files as well.

**Comment by 1campbellj** [comment]
This is happening pretty consistently for me if I switch between files very quickly.

1. Have multiple files in in the Staged Changes or Unstaged Changes portion of the git integration tab.
2. Switch rapidly between the diffs of the two files by clicking on one and then the other and back again quickly.

**Comment by oddvalue** [comment]
[Enter steps to reproduce:]

1. Open git panel.
2. Double click file in list to stage/unstage it before the diff has loaded on the left throws the error.
3. Clicking the file once, waiting for the diff to load, then double clicking works fine.


**Atom**: 1.27.1 x64
**Electron**: 1.7.15
**OS**: Mac OS X 10.13.4
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.8.2


### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:77:21)
    at StubItem.onDidChangeTitle (/Applications/Atom.app/Contents/Resources/app/node_modules/github/lib/atom-items/stub-item.js:125:31)
    at /packages/open-files/lib/open-files-pane-view.js:286:29
    at Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:1056:11)
    at Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:485:25)
    at /packages/open-files/lib/open-files-pane-view.js:232:21
```

### Commands

```
     -3:34.7.0 core:save-as (input.hidden-input)
  2x -3:23.6.0 core:backspace (input.hidden-input)
  2x -2:35.4.0 core:move-up (input.hidden-input)
     -2:34.9.0 docblockr:parse-enter (input.hidden-input)
     -2:34.9.0 editor:newline (input.hidden-input)
  3x -2:27.2.0 core:move-left (input.hidden-input)
     -2:25.5.0 editor:select-to-beginning-of-word (input.hidden-input)
     -2:24.7.0 datatip:toggle (input.hidden-input)
  3x -2:23.8.0 core:move-left (input.hidden-input)
     -2:20.1.0 docblockr:parse-tab (input.hidden-input)
     -2:20.1.0 autocomplete-plus:confirm (input.hidden-input)
     -2:19.5.0 core:move-right (input.hidden-input)
     -2:19.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
  4x -2:12.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.32.5 
atom-debug-ui 1.0.4 
atom-ide-ui 0.12.0 
busy-signal 1.4.3 
change-case 0.6.5 
craft-twig 0.4.0 
custom-title 1.0.1 
docblockr 0.13.7 
file-icons 2.1.21 
git-diff-details 1.4.0 
highlight-selected 0.13.1 
ide-php 0.7.14 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-markdown 0.25.1 
language-nunjucks 4.2.1 
linter 2.2.0 
linter-php 1.5.1 
linter-ui-default 1.7.1 
minimap 4.29.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
minimap-titles 1.15.0 
open-files 0.8.2 
php-debug 0.3.5 
php-ide-serenata 4.1.2 
php-twig 4.0.0 
pigments 0.40.2 
project-manager 3.3.6 
split-diff 1.5.2 
Sublime-Style-Column-Selection 1.7.4 
swackets 0.35.0 
tab-title 0.3.5 
terminal-tab 0.5.7 
text-pastry 0.6.1 
todo-show 2.3.0 
```
