### ISSUE TITLE
Uncaught TypeError: Cannot read property 'is' of null

### ISSUE THREAD

**Issue by iscjavierglez** [oriolmirosa/open-files#9]
[Enter steps to reproduce:]

1. ... Open project
2. ... Press Ctrl + K + B

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Professional 
**Thrown From**: [open-files](https://github.com/oriolmirosa/open-files) package 0.4.2

### Stack Trace

Uncaught TypeError: Cannot read property 'is' of null

```
At C:\Users\gonzalez.javier\.atom\packages\open-files\lib\open-files.js:31

TypeError: Cannot read property 'is' of null
    at /packages/open-files/lib/open-files.js:31:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:43.4.0 tree-view:toggle (input.hidden-input)
     -0:19.2.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:14.4.0 core:confirm (input.hidden-input)
     -0:13 find-and-replace:show (input.hidden-input)
  2x -0:10.5.0 core:confirm (input.hidden-input)
     -0:08.6.0 core:backspace (input.hidden-input)
  5x -0:08.4.0 core:confirm (input.hidden-input)
  2x -0:00.9.0 core:move-down (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-snippets 0.10.18 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-html-preview 0.1.22 
autoclose-html 0.23.0 
autocomplete-json 5.4.0 
autocomplete-xml 0.9.4 
file-explorer 0.3.0 
git-control 0.9.0 
highlight-selected 0.13.1 
open-files 0.4.2 
open-recent 5.0.0 
tree-view-open-files 0.3.0 
xml-formatter 0.10.0 
```

**Comment by oriolmirosa** [comment]
I just pushed a release that, hopefully, will take care of this (as well as other related problems). I'll close the issue, but please re-open it and let me know if the problem persists.
